In [17]:
import numpy as np
import pandas as pd
import random

In [58]:
def index_win_ratio(a, b, n):

    N = 10_000

    result = {"first": 0, "second": 0}

    for i in range(N):
        # while loop for each heads and tails case

#         lastflip, thisflip = "U", "U"
#         while True:
#             number = random.randint(0, 1)
#             if number == 0:
#                 thisflip = "H"
#             else:
#                 thisflip = "T"

#             if lastflip + thisflip == a:
#                 result[a] += 1
#                 break
#             if lastflip + thisflip == b:
#                 result[b] += 1
#                 break
#             lastflip = thisflip

        flips = np.zeros(n)
        while True:
            for j in range(1, n):
                flips[j - 1] = flips[j]
                
            number = random.randint(1, 2)
            flips[n - 1] = number
            
            if (flips == a).all():
                result["first"] += 1
                break
            if (flips == b).all():
                result["second"] += 1
                break
                
    return result["first"] / (result["first"] + result["second"])

In [59]:
def make_arrays(n):
    if n == 1:
        return [np.array([1]), np.array([2])]
    arrays = []
    for i in [1, 2]:
        for array in make_arrays(n - 1):
            arrays.append(np.append(array, i))
    return arrays

In [61]:
n = 3
arr = make_arrays(n)
dfindex = []
for a in arr:
    dfindex.append(np.array2string(a))
df = pd.DataFrame(index = dfindex, columns = dfindex)
for a in arr:
    for b in arr:
        df.loc[np.array2string(a), np.array2string(b)] = index_win_ratio(a, b, n)
df

[1 1 1] [2 1 1] [1 2 1] [2 2 1] [1 1 2] [2 1 2] [1 2 2] [2 2 2]
[1 1 1]     1.0  0.1242  0.4006  0.3029  0.4997  0.4112  0.4048  0.4947
[2 1 1]  0.8656     1.0  0.4975   0.339  0.7522  0.4949  0.5079  0.5994
[1 2 1]  0.6093  0.4938     1.0  0.3677  0.3349  0.4975  0.5032  0.5821
[2 2 1]  0.6951  0.6642  0.6223     1.0  0.4945  0.6643  0.2492  0.4997
[1 1 2]  0.5055  0.2437  0.6697  0.5033     1.0  0.6317  0.6671   0.703
[2 1 2]  0.5889  0.5011  0.4921  0.3319  0.3729     1.0  0.4986  0.6065
[1 2 2]  0.6083  0.5097  0.5041  0.7394  0.3265  0.4991     1.0  0.8783
[2 2 2]  0.4982  0.4011  0.4272  0.5019  0.2962  0.3956  0.1244     1.0