In [60]:
import numpy as np
import pandas as pd
import random

Players: 2

Characters:         m

Checking Length:    n

In [61]:
def index_win_ratio(a, b, n):
    N = 100_000

    result = {"first": 0, "second": 0}

    for i in range(N):
        # while loop for each heads and tails case
        flips = np.zeros(n)
        while True:
            for j in range(1, n):
                flips[j - 1] = flips[j]

            number = random.randint(1, 2)
            
            flips[n - 1] = number
        
            if (flips == a).all():
                result["first"] += 1
                break
            if (flips == b).all():
                result["second"] += 1
                break

    return result["first"] / (result["first"] + result["second"])

In [62]:
def make_arrays(n):
    if n == 1:
        return [np.array([1]), np.array([2])]
    
    arrays = []
    for i in [1, 2]:
        for array in make_arrays(n - 1):
            arrays.append(np.append(array, i))

    return arrays

In [63]:
n = 3
arr = make_arrays(n)

indexes = []

for i in arr:
    indexes.append(np.array2string(i))

dataframe = pd.DataFrame(index = indexes, columns = indexes)

for a in arr:
    for b in arr:
        dataframe.loc[np.array2string(a), np.array2string(b)] = index_win_ratio(a, b, n)

dataframe

[1 1 1]  [2 1 1]  [1 2 1]  [2 2 1]  [1 1 2]  [2 1 2]  [1 2 2]  \
[1 1 1]      1.0   0.1268  0.39975  0.30054  0.49941  0.41864  0.40049   
[2 1 1]  0.87424      1.0  0.49864  0.33288  0.75234  0.50175   0.5011   
[1 2 1]      0.6  0.49885      1.0  0.37609  0.33182  0.50401   0.5007   
[2 2 1]  0.70037  0.66373  0.62336      1.0  0.50055   0.6678  0.25015   
[1 1 2]  0.49925  0.25069  0.66365  0.50031      1.0  0.62562  0.66634   
[2 1 2]  0.58515  0.50091  0.49862  0.33273  0.37401      1.0  0.50287   
[1 2 2]  0.60076  0.49779  0.49913  0.74701  0.33319  0.49942      1.0   
[2 2 2]  0.50129  0.40132  0.41598  0.50023  0.29914  0.40136  0.12609   

         [2 2 2]  
[1 1 1]  0.50065  
[2 1 1]  0.59931  
[1 2 1]  0.58582  
[2 2 1]  0.50034  
[1 1 2]  0.70083  
[2 1 2]  0.60083  
[1 2 2]  0.87512  
[2 2 2]      1.0