In [13]:
import math
import numpy as np
import csv
import itertools

In [14]:
def create_cases(num_of_chars: int, length_of_case: int) -> list[np.ndarray]:
    return [np.array(i) for i in itertools.product(range(num_of_chars), repeat = length_of_case)]

In [15]:
def record_on_csv(number_of_characters: int, length_of_case: int, cases: list, dictionary: dict) -> None:
    with open("./martingale_results/expected_values_17.csv", 'a') as function:
        writer = csv.writer(function)
        for i in range(len(cases)):
            writer.writerow([number_of_characters, length_of_case, np.array2string(cases[i]), dictionary[np.array2string(cases[i])]])

In [16]:
def expected_values(num_of_chars: int, length_of_case: int) -> tuple[dict[str, float], list[np.ndarray]]:
    cases = create_cases(num_of_chars, length_of_case)
    case_value_dictionary = {}
    
    for case in cases:
        expected_value = math.pow(num_of_chars, length_of_case)
        for i in range(length_of_case - 1):
            test = case[i + 1:]
            power = 0
            for j in range(length_of_case - (i + 2), -1, -1):
                if test[j] == case[j]:
                    power += 1
                else:
                    break
            if power != 0:
                expected_value += math.pow(num_of_chars, power)
    
        case_value_dictionary[np.array2string(case)] = expected_value
    
    return case_value_dictionary, cases

In [17]:
def main():
    m = int(input("Number of Characters: "))
    n = int(input("Length of Case: "))
    
    exp_val = expected_values(num_of_chars=m, length_of_case=n)
    
    dictionary = exp_val[0]
    cases = exp_val[1]
        
    for i in range(len(cases)):
        key = np.array2string(cases[i])
        print(key,":", dictionary[key])

In [18]:
if __name__=='__main__':
    main()

[0 0 0] : 14.0
[0 0 1] : 8.0
[0 1 0] : 10.0
[0 1 1] : 10.0
[1 0 0] : 10.0
[1 0 1] : 10.0
[1 1 0] : 8.0
[1 1 1] : 14.0
