## IMPORT PACAKAGES

In [36]:
# importing required packages

import numpy as np
import pandas as pd
import random
import statistics
from tqdm import tqdm

## DEFINE FUNCTIONS

In [37]:
# Calculate the probability of one winning over the other

def index_win_ratio(a, b, m, n):
    N = 100_000 # Trial 100,000 times

    result = {"first": 0, "second": 0}

    for i in range(N):
        # while loop for each heads and tails case
        flips = np.zeros(n)
        while True:
            for j in range(1, n):
                flips[j - 1] = flips[j]

            number = random.randint(1, m)
            
            flips[n - 1] = number
        
            if (flips == a).all():
                result["first"] += 1
                break
            if (flips == b).all():
                result["second"] += 1
                break

    return [ result["first"] / (result["first"] + result["second"]), result["second"] / (result["first"] + result["second"]) ]

In [38]:
# Create the array set for the indexes and columns of the dataframe

def make_arrays(m, n):
    if n == 1:
        arr = []

        for i in range(1, m + 1):
            arr.append(np.array([i]))

        return arr
    
    arrays = []
    for i in range(1, m + 1):
        for array in make_arrays(m, n - 1):
            arrays.append(np.append(array, i))

    return arrays

## CALCULATION

In [39]:
m = 3
n = 3

arr = make_arrays(m, n)

indexes = []
for i in arr:
    indexes.append(np.array2string(i))

df = pd.DataFrame(index=indexes, columns=indexes)

for i in tqdm(range(0, len(arr))):
    for j in tqdm(range(i, len(arr))):

        if (i == j):
            res = [1.0, 1.0]

        else:
            res = index_win_ratio(arr[i], arr[j], m, n)

        df.loc[np.array2string(arr[i]), np.array2string(arr[j])] = res[0]
        df.loc[np.array2string(arr[j]), np.array2string(arr[i])] = res[1]

df

100%|██████████| 27/27 [34:09<00:00, 75.92s/it]


[1 1 1]  [2 1 1]  [3 1 1]  [1 2 1]  [2 2 1]  [3 2 1]  [1 3 1]  \
[1 1 1]      1.0  0.27976  0.28189  0.42918  0.38143  0.38369  0.42889   
[2 1 1]  0.72024      1.0  0.49956  0.46795    0.401  0.40006  0.55439   
[3 1 1]  0.71811  0.50044      1.0  0.55062  0.49955  0.49926  0.46744   
[1 2 1]  0.57082  0.53205  0.44938      1.0  0.44601  0.44202  0.49888   
[2 2 1]  0.61857    0.599  0.50045  0.55399      1.0  0.50155  0.55618   
[3 2 1]  0.61631  0.59994  0.50074  0.55798  0.49845      1.0    0.555   
[1 3 1]  0.57111  0.44561  0.53256  0.50112  0.44382    0.445      1.0   
[2 3 1]  0.62053  0.49798  0.59847  0.55554  0.49973  0.50121  0.55833   
[3 3 1]  0.61726  0.50142  0.60047  0.55657   0.4979  0.50012  0.55532   
[1 1 2]  0.49976  0.38272  0.35681  0.59694  0.49801   0.4707  0.50113   
[2 1 2]  0.56506  0.49838  0.47399  0.50016  0.40214  0.37701  0.49849   
[3 1 2]   0.5884  0.52971   0.4979  0.62524  0.53126  0.50059  0.44198   
[1 2 2]  0.57044  0.50002  0.47095  0.49661  0.61486  0.47124   0.4993   
[2 2 2]  0.49839  0.42946  0.41012  0.43624  0.49928  0.40911  0.43552   
[3 2 2]  0.59142  0.52772  0.49986  0.52536  0.64267  0.50112  0.52749   
[1 3 2]   0.5693  0.49977  0.47039  0.49823  0.50356  0.57258  0.49903   
[2 3 2]  0.56582  0.49884  0.47237  0.49926  0.50185  0.56071  0.49892   
[3 3 2]  0.59264  0.52746  0.49997  0.52334   0.5291  0.59843  0.52901   
[1 1 3]   0.5022  0.35509  0.38211  0.49832  0.47108  0.50031  0.59849   
[2 1 3]  0.59102  0.50192  0.52972  0.43878  0.40131  0.42791   0.6249   
[3 1 3]  0.56661  0.47318  0.49944  0.50248  0.47305    0.501  0.50089   
[1 2 3]   0.5736  0.47067    0.499  0.49738   0.4711  0.49803  0.49871   
[2 2 3]  0.59227  0.49857  0.53053  0.52484  0.50021  0.52773  0.52661   
[3 2 3]  0.56274  0.47406  0.50002  0.50267  0.47377  0.49822  0.50162   
[1 3 3]  0.56986  0.47021  0.50025  0.49935   0.4725  0.49921   0.4982   
[2 3 3]   0.5919  0.49521  0.53031  0.52627  0.49805  0.52927  0.52832   
[3 3 3]  0.50224  0.40973  0.42826  0.43429  0.40972   0.4281  0.43422   

         [2 3 1]  [3 3 1]  [1 1 2]  ...  [3 3 2]  [1 1 3]  [2 1 3]  [3 1 3]  \
[1 1 1]  0.37947  0.38274  0.50024  ...  0.40736   0.4978  0.40898  0.43339   
[2 1 1]  0.50202  0.49858  0.61728  ...  0.47254  0.64491  0.49808  0.52682   
[3 1 1]  0.40153  0.39953  0.64319  ...  0.50003  0.61789  0.47028  0.50056   
[1 2 1]  0.44446  0.44343  0.40306  ...  0.47666  0.50168  0.56122  0.49752   
[2 2 1]  0.50027   0.5021  0.50199  ...   0.4709  0.52892  0.59869  0.52695   
[3 2 1]  0.49879  0.49988   0.5293  ...  0.40157  0.49969  0.57209    0.499   
[1 3 1]  0.44167  0.44468  0.49887  ...  0.47099  0.40151   0.3751  0.49911   
[2 3 1]      1.0  0.50042  0.49957  ...  0.46867  0.53137  0.50046   0.6228   
[3 3 1]  0.49958      1.0  0.53162  ...  0.50065  0.49921  0.47314  0.59895   
[1 1 2]  0.50043  0.46838      1.0  ...   0.5028  0.49768  0.53143  0.52584   
[2 1 2]  0.50104  0.47247  0.44659  ...  0.44297    0.473  0.49755  0.50011   
[3 1 2]  0.42759  0.39902  0.49836  ...  0.50051  0.47121  0.50286  0.49891   
[1 2 2]  0.49859  0.47022  0.40026  ...  0.50047  0.50171  0.52886   0.5277   
[2 2 2]  0.42774  0.40626  0.38153  ...  0.38124  0.40726  0.42891  0.43577   
[3 2 2]  0.53025  0.49949  0.50011  ...  0.40115  0.47041  0.49913  0.49876   
[1 3 2]  0.50236   0.4695   0.4985  ...  0.49859   0.4006  0.43055  0.43719   
[2 3 2]  0.49998  0.47188  0.44407  ...  0.44342  0.47201  0.50148  0.50191   
[3 3 2]  0.53133  0.49935   0.4972  ...      1.0  0.46952  0.50163  0.50044   
[1 1 3]  0.46863  0.50079  0.50232  ...  0.53048      1.0  0.50173  0.55657   
[2 1 3]  0.49954  0.52686  0.46857  ...  0.49837  0.49827      1.0  0.55466   
[3 1 3]   0.3772  0.40105  0.47416  ...  0.49956  0.44343  0.44534      1.0   
[1 2 3]  0.57396  0.49842  0.39894  ...  0.53028  0.50058  0.49851  0.55692   
[2 2 3]  0.60027  0.53024  0.46952  ...  0.49988  0.50036  0.50161  0.55393   
[3 2 3]  0.56218   0.5007  0.47342  ... 

## EVALUATIONS

In [40]:
results = []

for i in range(0, len(indexes) - 1):
    for j in range(i + 1, len(indexes)):
        results.append((df.loc[indexes[i], indexes[j]] + df.loc[indexes[j], indexes[i]]))

print(statistics.mean(results))

1.0


In [41]:
with open('results.txt', 'a') as function:
    function.writelines("m : " + str(m) + "\nn : " + str(n) + "\n\n")
    for i in indexes:
        for j in indexes:
            function.writelines("[ " + i + ", " + j + " ]: " + str(df.loc[i, j]) + "\n")
        function.writelines("\n")
    function.writelines("------------------------------\n\n")

## RESULTS


The time required to perform on a 2^3 * 2^3 dataframe took significantly less time as the time required decreased from 2' 36.2" to 1' 3.6"

Formulated Time of the "Process" section excluding the make_arrays function: (m^(2n)) * (m^n + 1) * n * N / 4