In [64]:
import numpy as np
import pandas as pd
import random

Players: 2

Characters:         m

Checking Length:    n

In [65]:
def index_win_ratio(a, b, n):
    N = 100_000

    result = {"first": 0, "second": 0}

    for i in range(N):
        # while loop for each heads and tails case
        flips = np.zeros(n)
        while True:
            for j in range(1, n):
                flips[j - 1] = flips[j]

            number = random.randint(1, 2)
            
            flips[n - 1] = number
        
            if (flips == a).all():
                result["first"] += 1
                break
            if (flips == b).all():
                result["second"] += 1
                break

    return result["first"] / (result["first"] + result["second"])

In [66]:
def make_arrays(n):
    if n == 1:
        return [np.array([1]), np.array([2])]
    
    arrays = []
    for i in [1, 2]:
        for array in make_arrays(n - 1):
            arrays.append(np.append(array, i))

    return arrays

In [67]:
n = 3
arr = make_arrays(n)

indexes = []

for i in arr:
    indexes.append(np.array2string(i))

dataframe = pd.DataFrame(index = indexes, columns = indexes)

for a in arr:
    for b in arr:
        dataframe.loc[np.array2string(a), np.array2string(b)] = index_win_ratio(a, b, n)

dataframe

[1 1 1]  [2 1 1]  [1 2 1]  [2 2 1]  [1 1 2]  [2 1 2]  [1 2 2]  \
[1 1 1]      1.0  0.12387   0.4026  0.30441  0.49962  0.41843   0.4004   
[2 1 1]  0.87482      1.0  0.49965   0.3333  0.74694  0.49964  0.50103   
[1 2 1]  0.60093    0.502      1.0  0.37405  0.33333   0.5036  0.50434   
[2 2 1]  0.70002  0.66539  0.62728      1.0  0.49952  0.66771  0.25055   
[1 1 2]  0.50085  0.25231  0.66765  0.49924      1.0  0.62441  0.66768   
[2 1 2]  0.58414  0.50127   0.4986  0.33483  0.37548      1.0   0.5017   
[1 2 2]  0.59934  0.49906  0.49913  0.75047  0.33189  0.49709      1.0   
[2 2 2]  0.49944  0.40038  0.41584  0.49908   0.3034  0.40068  0.12459   

         [2 2 2]  
[1 1 1]  0.49979  
[2 1 1]  0.59851  
[1 2 1]  0.58443  
[2 2 1]  0.50054  
[1 1 2]  0.69935  
[2 1 2]  0.60016  
[1 2 2]  0.87411  
[2 2 2]      1.0