## IMPORT PACKAGES

In [1]:
# importing required packages

import numpy as np
import pandas as pd
import random
import statistics
from tqdm import tqdm

## DEFINE FUNCTIONS

In [2]:
# Calculate the probability of one winning over the other

def index_win_ratio(a, b, m: int, n: int):
    N = 100_000 # Trial 100,000 times

    result = {"first": 0, "second": 0}

    for i in range(N):
        # while loop for each heads and tails case
        flips = np.zeros(n)
        while True:
            for j in range(1, n):
                flips[j - 1] = flips[j]

            number = random.randint(1, m)
            
            flips[n - 1] = number
        
            if (flips == a).all():
                result["first"] += 1
                break
            if (flips == b).all():
                result["second"] += 1
                break

    return [ result["first"] / (result["first"] + result["second"]), result["second"] / (result["first"] + result["second"]) ]

In [3]:
# Create the array set for the indexes and columns of the dataframe

def make_arrays(m: int, n: int):
    if n == 1:
        arr = []

        for i in range(1, m + 1):
            arr.append(np.array([i]))

        return arr
    
    arrays = []
    for i in range(1, m + 1):
        for array in make_arrays(m, n - 1):
            arrays.append(np.append(array, i))

    return arrays

## CALCULATION

In [4]:
m = 3
n = 3

arr = make_arrays(m, n)

indexes = []
for i in arr:
    indexes.append(np.array2string(i))

df = pd.DataFrame(index=indexes, columns=indexes)

for i in tqdm(range(0, len(arr))):
    for j in tqdm(range(i, len(arr))):

        if i == j:
            res = [1.0, 1.0]

        else:
            res = index_win_ratio(arr[i], arr[j], m, n)

        df.loc[np.array2string(arr[i]), np.array2string(arr[j])] = res[0]
        df.loc[np.array2string(arr[j]), np.array2string(arr[i])] = res[1]

df

100%|██████████| 27/27 [34:14<00:00, 76.11s/it]


[1 1 1]  [2 1 1]  [3 1 1]  [1 2 1]  [2 2 1]  [3 2 1]  [1 3 1]  \
[1 1 1]      1.0  0.27892  0.27582  0.42953  0.38224  0.38016  0.42623   
[2 1 1]  0.72108      1.0  0.49854  0.46828  0.39771  0.40258  0.55583   
[3 1 1]  0.72418  0.50146      1.0  0.55624  0.49694  0.50157  0.46462   
[1 2 1]  0.57047  0.53172  0.44376      1.0  0.44492  0.44527  0.49884   
[2 2 1]  0.61776  0.60229  0.50306  0.55508      1.0  0.49961   0.5558   
[3 2 1]  0.61984  0.59742  0.49843  0.55473  0.50039      1.0   0.5567   
[1 3 1]  0.57377  0.44417  0.53538  0.50116   0.4442   0.4433      1.0   
[2 3 1]  0.61953  0.50136  0.59681  0.55536  0.49903  0.50049  0.55603   
[3 3 1]  0.61815  0.50064  0.59729  0.55273   0.5005  0.50018   0.5549   
[1 1 2]  0.50018  0.38331  0.35793   0.5989  0.49955  0.46886  0.50014   
[2 1 2]  0.56571  0.50053  0.47492  0.50351  0.39905  0.37327  0.49777   
[3 1 2]  0.58898  0.53436  0.49805  0.62053  0.53062  0.49882  0.43812   
[1 2 2]  0.57073  0.49915  0.46943  0.49928  0.61475  0.47091  0.50066   
[2 2 2]  0.50068  0.43013  0.40888   0.4362  0.49954  0.40555  0.43539   
[3 2 2]  0.59159  0.52907  0.49636  0.52388  0.64096  0.50191  0.52379   
[1 3 2]  0.57201  0.49962  0.47101  0.49997  0.49968  0.57416   0.4965   
[2 3 2]  0.56463  0.49968  0.47488   0.4996  0.49837   0.5628  0.50051   
[3 3 2]   0.5881  0.53043  0.49993  0.52484  0.52725  0.59716   0.5249   
[1 1 3]  0.50116  0.35626  0.38607  0.50061  0.46961  0.50069  0.59992   
[2 1 3]  0.59187  0.49818  0.53056   0.4378  0.39773  0.42705  0.62744   
[3 1 3]  0.56522  0.47196  0.49974  0.50017   0.4741  0.49895  0.49833   
[1 2 3]  0.56957  0.46825  0.50012  0.49933  0.46994  0.50505  0.50289   
[2 2 3]  0.59209  0.50082  0.53113  0.52494  0.50056  0.53027  0.52591   
[3 2 3]  0.56334  0.47472  0.49981  0.50205  0.47533  0.50104  0.49943   
[1 3 3]  0.57018  0.47118   0.4983  0.49765  0.47132  0.50313  0.50068   
[2 3 3]  0.58968  0.50332  0.52867  0.52567  0.50073  0.53024  0.52579   
[3 3 3]  0.49929  0.40875  0.43008  0.43428   0.4094  0.42928  0.43731   

         [2 3 1]  [3 3 1]  [1 1 2]  ...  [3 3 2]  [1 1 3]  [2 1 3]  [3 1 3]  \
[1 1 1]  0.38047  0.38185  0.49982  ...   0.4119  0.49884  0.40813  0.43478   
[2 1 1]  0.49864  0.49936  0.61669  ...  0.46957  0.64374  0.50182  0.52804   
[3 1 1]  0.40319  0.40271  0.64207  ...  0.50007  0.61393  0.46944  0.50026   
[1 2 1]  0.44464  0.44727   0.4011  ...  0.47516  0.49939   0.5622  0.49983   
[2 2 1]  0.50097   0.4995  0.50045  ...  0.47275  0.53039  0.60227   0.5259   
[3 2 1]  0.49951  0.49982  0.53114  ...  0.40284  0.49931  0.57295  0.50105   
[1 3 1]  0.44397   0.4451  0.49986  ...   0.4751  0.40008  0.37256  0.50167   
[2 3 1]      1.0  0.49924   0.5002  ...  0.47096  0.52899   0.5001  0.62613   
[3 3 1]  0.50076      1.0  0.52922  ...  0.50143  0.49724  0.47441  0.60007   
[1 1 2]   0.4998  0.47078      1.0  ...   0.5006  0.50107  0.53259    0.527   
[2 1 2]  0.49893  0.47531   0.4448  ...  0.44358  0.47387  0.50253  0.50176   
[3 1 2]  0.42809  0.40294  0.49937  ...  0.50137  0.47093  0.50108  0.50148   
[1 2 2]  0.49883  0.47263  0.40048  ...  0.50051  0.49992  0.52788  0.52705   
[2 2 2]  0.42967  0.40617  0.38205  ...  0.38182  0.40896  0.42782  0.43472   
[3 2 2]  0.52691  0.50251  0.49927  ...  0.40156  0.47078  0.50011  0.49727   
[1 3 2]  0.49973  0.46827  0.49813  ...  0.49767  0.40174  0.42801  0.43613   
[2 3 2]  0.49844  0.47134  0.44622  ...   0.4428  0.47301  0.49916  0.50025   
[3 3 2]  0.52904  0.49857   0.4994  ...      1.0   0.4721  0.49861  0.49895   
[1 1 3]  0.47101  0.50276  0.49893  ...   0.5279      1.0   0.4985  0.55732   
[2 1 3]   0.4999  0.52559  0.46741  ...  0.50139   0.5015      1.0  0.55469   
[3 1 3]  0.37387  0.39993    0.473  ...  0.50105  0.44268  0.44531      1.0   
[1 2 3]  0.57371  0.50213  0.40182  ...  0.52809    0.499  0.49902  0.55317   
[2 2 3]  0.59857  0.52905  0.47056  ...   0.4977  0.50127  0.49825  0.55414   
[3 2 3]  0.56544  0.49982  0.47358  ... 

## EVALUATIONS

In [5]:
results = []

for i in range(0, len(indexes) - 1):
    for j in range(i + 1, len(indexes)):
        results.append((df.loc[indexes[i], indexes[j]] + df.loc[indexes[j], indexes[i]]))

print(statistics.mean(results))

1.0


In [6]:
with open('results.txt', 'a') as function:
    function.writelines("m : " + str(m) + "\nn : " + str(n) + "\n\n")
    for i in indexes:
        for j in indexes:
            function.writelines("[ " + i + ", " + j + " ]: " + str(df.loc[i, j]) + "\n")
        function.writelines("\n")
    function.writelines("------------------------------\n\n")

## RESULTS