In [114]:
import string
import math
import numpy as np

In [115]:
tmp = string.digits + string.ascii_lowercase
def convert_base(num: int, base: int):
    q, r = divmod(num, base)
    if q == 0:
        return tmp[r]
    else:
        return convert_base(q, base) + tmp[r]

In [116]:
def create_cases(num_of_chars: int, length_of_case: int):
    cases = []
    for i in range(int(math.pow(num_of_chars, length_of_case))):
        result = convert_base(i, num_of_chars)
        absorbing_state = np.array([])
        for j in range(length_of_case - len(result)):
            absorbing_state = np.append(absorbing_state, 0)
        for j in range(len(result)):
            if 48 <= ord(result[j]) <= 57:
                absorbing_state = np.append(absorbing_state, int(result[j]))
            else:
                absorbing_state = np.append(absorbing_state, int(ord(result[j]) - 87))
        cases.append(absorbing_state)
    
    return cases

In [117]:
def expected_values(num_of_chars: int, length_of_case: int) -> dict:
    cases = create_cases(num_of_chars, length_of_case)
    case_value_dictionary = {}
    
    for case in cases:
        # print(np.array2string(case) + ": ")
        expected_value = math.pow(num_of_chars, length_of_case)
        for i in range(1, length_of_case):
            test = case[i:]
            # print("Test case " + np.array2string(test) + ": ", end="")
            power = 0
            for j in range(length_of_case - i):
                if test[j] == case[j]:
                    power += 1
                else:
                    break
            if power != 0:
                expected_value += math.pow(num_of_chars, power)
            # print(expected_value)
    
        case_value_dictionary[np.array2string(case)] = expected_value
    
    return case_value_dictionary

In [118]:
def main():
    m = int(input("Number of Characters: "))
    n = int(input("Length of Case: "))
    
    dictionary = expected_values(m, n)
    cases = create_cases(m, n)
    
    for i in range(len(cases)):
        print(np.array2string(cases[i]), dictionary[np.array2string(cases[i])])

In [119]:
if __name__=='__main__':
    main()

[0. 0. 0. 0. 0. 0.] 126.0
[0. 0. 0. 0. 0. 1.] 94.0
[0. 0. 0. 0. 1. 0.] 80.0
[0. 0. 0. 0. 1. 1.] 78.0
[0. 0. 0. 1. 0. 0.] 76.0
[0. 0. 0. 1. 0. 1.] 72.0
[0. 0. 0. 1. 1. 0.] 72.0
[0. 0. 0. 1. 1. 1.] 70.0
[0. 0. 1. 0. 0. 0.] 76.0
[0. 0. 1. 0. 0. 1.] 76.0
[0. 0. 1. 0. 1. 0.] 70.0
[0. 0. 1. 0. 1. 1.] 68.0
[0. 0. 1. 1. 0. 0.] 72.0
[0. 0. 1. 1. 0. 1.] 68.0
[0. 0. 1. 1. 1. 0.] 68.0
[0. 0. 1. 1. 1. 1.] 66.0
[0. 1. 0. 0. 0. 0.] 72.0
[0. 1. 0. 0. 0. 1.] 72.0
[0. 1. 0. 0. 1. 0.] 76.0
[0. 1. 0. 0. 1. 1.] 70.0
[0. 1. 0. 1. 0. 0.] 76.0
[0. 1. 0. 1. 0. 1.] 84.0
[0. 1. 0. 1. 1. 0.] 70.0
[0. 1. 0. 1. 1. 1.] 68.0
[0. 1. 1. 0. 0. 0.] 70.0
[0. 1. 1. 0. 0. 1.] 70.0
[0. 1. 1. 0. 1. 0.] 70.0
[0. 1. 1. 0. 1. 1.] 72.0
[0. 1. 1. 1. 0. 0.] 68.0
[0. 1. 1. 1. 0. 1.] 68.0
[0. 1. 1. 1. 1. 0.] 66.0
[0. 1. 1. 1. 1. 1.] 64.0
[1. 0. 0. 0. 0. 0.] 64.0
[1. 0. 0. 0. 0. 1.] 66.0
[1. 0. 0. 0. 1. 0.] 68.0
[1. 0. 0. 0. 1. 1.] 68.0
[1. 0. 0. 1. 0. 0.] 72.0
[1. 0. 0. 1. 0. 1.] 70.0
[1. 0. 0. 1. 1. 0.] 70.0
[1. 0. 0. 1. 1. 1.] 70.0